/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAutopilotRouteImport } from './routes/_app.autopilot'
import { Route as AppBoardRouteImport } from './routes/_app.board'
import { Route as AppBriefHistoryRouteImport } from './routes/_app.brief-history'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppCharactersRouteImport } from './routes/_app.characters'
import { Route as AppContentScoreRouteImport } from './routes/_app.content-score'
import { Route as AppDailyBriefRouteImport } from './routes/_app.daily-brief'
import { Route as AppDmRouteImport } from './routes/_app.dm'
import { Route as AppHookScoreboardRouteImport } from './routes/_app.hook-scoreboard'
import { Route as AppIdeatorRouteImport } from './routes/_app.ideator'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppScriptRouteImport } from './routes/_app.script'
import { Route as AppSeriesRouteImport } from './routes/_app.series'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppStoryboardRouteImport } from './routes/_app.storyboard'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppThumbnailStudioRouteImport } from './routes/_app.thumbnail-studio'
import { Route as AppVideoAnalyzerRouteImport } from './routes/_app.video-analyzer'
import { Route as AppVideoPromptRouteImport } from './routes/_app.video-prompt'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiApifyUsageRouteImport } from './routes/api/apify-usage'
import { Route as ApiAppearanceRouteImport } from './routes/api/appearance'
import { Route as ApiAutoQueueRouteImport } from './routes/api/auto-queue'
import { Route as ApiBoardRouteImport } from './routes/api/board'
import { Route as ApiBoardAttachRouteImport } from './routes/api/board-attach'
import { Route as ApiBriefRouteImport } from './routes/api/brief'
import { Route as ApiCharactersRouteImport } from './routes/api/characters'
import { Route as ApiDmRouteImport } from './routes/api/dm'
import { Route as ApiFrameCheckRouteImport } from './routes/api/frame-check'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGeneratePlanRouteImport } from './routes/api/generate-plan'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHookScriptWriterRouteImport } from './routes/api/hook-script-writer'
import { Route as ApiHooksRouteImport } from './routes/api/hooks'
import { Route as ApiIdeatorGenerateRouteImport } from './routes/api/ideator-generate'
import { Route as ApiLibraryExportRouteImport } from './routes/api/library-export'
import { Route as ApiLibraryImportRouteImport } from './routes/api/library-import'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiPillarsRouteImport } from './routes/api/pillars'
import { Route as ApiPlatformVariantsRouteImport } from './routes/api/platform-variants'
import { Route as ApiPostPerformanceRouteImport } from './routes/api/post-performance'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiReaderRouteImport } from './routes/api/reader'
import { Route as ApiResourcesRouteImport } from './routes/api/resources'
import { Route as ApiRunPipelineRouteImport } from './routes/api/run-pipeline'
import { Route as ApiScoreContentRouteImport } from './routes/api/score-content'
import { Route as ApiScrapeCompetitorRouteImport } from './routes/api/scrape-competitor'
import { Route as ApiScriptsListRouteImport } from './routes/api/scripts-list'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSettingsImagegenRouteImport } from './routes/api/settings-imagegen'
import { Route as ApiTelegramChatIdRouteImport } from './routes/api/telegram-chat-id'
import { Route as ApiTelegramCronRouteImport } from './routes/api/telegram-cron'
import { Route as ApiTelegramHookRouteImport } from './routes/api/telegram-hook'
import { Route as ApiTelegramTasksRouteImport } from './routes/api/telegram-tasks'
import { Route as ApiTelegramTestRouteImport } from './routes/api/telegram-test'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram-webhook'
import { Route as ApiThumbnailPromptRouteImport } from './routes/api/thumbnail-prompt'
import { Route as ApiTrendSpyRouteImport } from './routes/api/trend-spy'
import { Route as ApiTrendsRouteImport } from './routes/api/trends'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiVideoAnalyzerRouteImport } from './routes/api/video-analyzer'
import { Route as ApiVideoGenPromptRouteImport } from './routes/api/video-gen-prompt'
import { Route as ApiVisualStoryboardRouteImport } from './routes/api/visual-storyboard'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiLibraryTypeRouteImport } from './routes/api/library.$type'
import { Route as ApiResourcesIdRouteImport } from './routes/api/resources.$id'
import { Route as ApiWorkspaceSelected_ideaRouteImport } from './routes/api/workspace.selected_idea'
import { Route as ApiLibraryTypeIdRouteImport } from './routes/api/library.$type.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutopilotRoute = AppAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefHistoryRoute = AppBriefHistoryRouteImport.update({
  id: '/brief-history',
  path: '/brief-history',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersRoute = AppCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AppRoute,
} as any)
const AppContentScoreRoute = AppContentScoreRouteImport.update({
  id: '/content-score',
  path: '/content-score',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyBriefRoute = AppDailyBriefRouteImport.update({
  id: '/daily-brief',
  path: '/daily-brief',
  getParentRoute: () => AppRoute,
} as any)
const AppDmRoute = AppDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AppRoute,
} as any)
const AppHookScoreboardRoute = AppHookScoreboardRouteImport.update({
  id: '/hook-scoreboard',
  path: '/hook-scoreboard',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeatorRoute = AppIdeatorRouteImport.update({
  id: '/ideator',
  path: '/ideator',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptRoute = AppScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesRoute = AppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppStoryboardRoute = AppStoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppThumbnailStudioRoute = AppThumbnailStudioRouteImport.update({
  id: '/thumbnail-studio',
  path: '/thumbnail-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoAnalyzerRoute = AppVideoAnalyzerRouteImport.update({
  id: '/video-analyzer',
  path: '/video-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoPromptRoute = AppVideoPromptRouteImport.update({
  id: '/video-prompt',
  path: '/video-prompt',
  getParentRoute: () => AppRoute,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApifyUsageRoute = ApiApifyUsageRouteImport.update({
  id: '/api/apify-usage',
  path: '/api/apify-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppearanceRoute = ApiAppearanceRouteImport.update({
  id: '/api/appearance',
  path: '/api/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoQueueRoute = ApiAutoQueueRouteImport.update({
  id: '/api/auto-queue',
  path: '/api/auto-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardAttachRoute = ApiBoardAttachRouteImport.update({
  id: '/api/board-attach',
  path: '/api/board-attach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersRoute = ApiCharactersRouteImport.update({
  id: '/api/characters',
  path: '/api/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDmRoute = ApiDmRouteImport.update({
  id: '/api/dm',
  path: '/api/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrameCheckRoute = ApiFrameCheckRouteImport.update({
  id: '/api/frame-check',
  path: '/api/frame-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePlanRoute = ApiGeneratePlanRouteImport.update({
  id: '/api/generate-plan',
  path: '/api/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHookScriptWriterRoute = ApiHookScriptWriterRouteImport.update({
  id: '/api/hook-script-writer',
  path: '/api/hook-script-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksRoute = ApiHooksRouteImport.update({
  id: '/api/hooks',
  path: '/api/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIdeatorGenerateRoute = ApiIdeatorGenerateRouteImport.update({
  id: '/api/ideator-generate',
  path: '/api/ideator-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryExportRoute = ApiLibraryExportRouteImport.update({
  id: '/api/library-export',
  path: '/api/library-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryImportRoute = ApiLibraryImportRouteImport.update({
  id: '/api/library-import',
  path: '/api/library-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPillarsRoute = ApiPillarsRouteImport.update({
  id: '/api/pillars',
  path: '/api/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformVariantsRoute = ApiPlatformVariantsRouteImport.update({
  id: '/api/platform-variants',
  path: '/api/platform-variants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostPerformanceRoute = ApiPostPerformanceRouteImport.update({
  id: '/api/post-performance',
  path: '/api/post-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReaderRoute = ApiReaderRouteImport.update({
  id: '/api/reader',
  path: '/api/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunPipelineRoute = ApiRunPipelineRouteImport.update({
  id: '/api/run-pipeline',
  path: '/api/run-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoreContentRoute = ApiScoreContentRouteImport.update({
  id: '/api/score-content',
  path: '/api/score-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeCompetitorRoute = ApiScrapeCompetitorRouteImport.update({
  id: '/api/scrape-competitor',
  path: '/api/scrape-competitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptsListRoute = ApiScriptsListRouteImport.update({
  id: '/api/scripts-list',
  path: '/api/scripts-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsImagegenRoute = ApiSettingsImagegenRouteImport.update({
  id: '/api/settings-imagegen',
  path: '/api/settings-imagegen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramChatIdRoute = ApiTelegramChatIdRouteImport.update({
  id: '/api/telegram-chat-id',
  path: '/api/telegram-chat-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramCronRoute = ApiTelegramCronRouteImport.update({
  id: '/api/telegram-cron',
  path: '/api/telegram-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramHookRoute = ApiTelegramHookRouteImport.update({
  id: '/api/telegram-hook',
  path: '/api/telegram-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramTasksRoute = ApiTelegramTasksRouteImport.update({
  id: '/api/telegram-tasks',
  path: '/api/telegram-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramTestRoute = ApiTelegramTestRouteImport.update({
  id: '/api/telegram-test',
  path: '/api/telegram-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram-webhook',
  path: '/api/telegram-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbnailPromptRoute = ApiThumbnailPromptRouteImport.update({
  id: '/api/thumbnail-prompt',
  path: '/api/thumbnail-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendSpyRoute = ApiTrendSpyRouteImport.update({
  id: '/api/trend-spy',
  path: '/api/trend-spy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendsRoute = ApiTrendsRouteImport.update({
  id: '/api/trends',
  path: '/api/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAnalyzerRoute = ApiVideoAnalyzerRouteImport.update({
  id: '/api/video-analyzer',
  path: '/api/video-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenPromptRoute = ApiVideoGenPromptRouteImport.update({
  id: '/api/video-gen-prompt',
  path: '/api/video-gen-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualStoryboardRoute = ApiVisualStoryboardRouteImport.update({
  id: '/api/visual-storyboard',
  path: '/api/visual-storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryTypeRoute = ApiLibraryTypeRouteImport.update({
  id: '/api/library/$type',
  path: '/api/library/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesIdRoute = ApiResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiResourcesRoute,
} as any)
const ApiWorkspaceSelected_ideaRoute =
  ApiWorkspaceSelected_ideaRouteImport.update({
    id: '/selected_idea',
    path: '/selected_idea',
    getParentRoute: () => ApiWorkspaceRoute,
  } as any)
const ApiLibraryTypeIdRoute = ApiLibraryTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLibraryTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/autopilot': typeof AppAutopilotRoute
  '/board': typeof AppBoardRoute
  '/brief-history': typeof AppBriefHistoryRoute
  '/calendar': typeof AppCalendarRoute
  '/characters': typeof AppCharactersRoute
  '/content-score': typeof AppContentScoreRoute
  '/daily-brief': typeof AppDailyBriefRoute
  '/dm': typeof AppDmRoute
  '/hook-scoreboard': typeof AppHookScoreboardRoute
  '/ideator': typeof AppIdeatorRoute
  '/library': typeof AppLibraryRoute
  '/performance': typeof AppPerformanceRoute
  '/projects': typeof AppProjectsRoute
  '/resources': typeof AppResourcesRoute
  '/script': typeof AppScriptRoute
  '/series': typeof AppSeriesRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/storyboard': typeof AppStoryboardRoute
  '/templates': typeof AppTemplatesRoute
  '/thumbnail-studio': typeof AppThumbnailStudioRoute
  '/video-analyzer': typeof AppVideoAnalyzerRoute
  '/video-prompt': typeof AppVideoPromptRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/apify-usage': typeof ApiApifyUsageRoute
  '/api/appearance': typeof ApiAppearanceRoute
  '/api/auto-queue': typeof ApiAutoQueueRoute
  '/api/board': typeof ApiBoardRoute
  '/api/board-attach': typeof ApiBoardAttachRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/dm': typeof ApiDmRoute
  '/api/frame-check': typeof ApiFrameCheckRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hook-script-writer': typeof ApiHookScriptWriterRoute
  '/api/hooks': typeof ApiHooksRoute
  '/api/ideator-generate': typeof ApiIdeatorGenerateRoute
  '/api/library-export': typeof ApiLibraryExportRoute
  '/api/library-import': typeof ApiLibraryImportRoute
  '/api/me': typeof ApiMeRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/pillars': typeof ApiPillarsRoute
  '/api/platform-variants': typeof ApiPlatformVariantsRoute
  '/api/post-performance': typeof ApiPostPerformanceRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/reader': typeof ApiReaderRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/run-pipeline': typeof ApiRunPipelineRoute
  '/api/score-content': typeof ApiScoreContentRoute
  '/api/scrape-competitor': typeof ApiScrapeCompetitorRoute
  '/api/scripts-list': typeof ApiScriptsListRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/settings-imagegen': typeof ApiSettingsImagegenRoute
  '/api/telegram-chat-id': typeof ApiTelegramChatIdRoute
  '/api/telegram-cron': typeof ApiTelegramCronRoute
  '/api/telegram-hook': typeof ApiTelegramHookRoute
  '/api/telegram-tasks': typeof ApiTelegramTasksRoute
  '/api/telegram-test': typeof ApiTelegramTestRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/thumbnail-prompt': typeof ApiThumbnailPromptRoute
  '/api/trend-spy': typeof ApiTrendSpyRoute
  '/api/trends': typeof ApiTrendsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/video-analyzer': typeof ApiVideoAnalyzerRoute
  '/api/video-gen-prompt': typeof ApiVideoGenPromptRoute
  '/api/visual-storyboard': typeof ApiVisualStoryboardRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/resources/$id': typeof ApiResourcesIdRoute
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRoutesByTo {
  '/autopilot': typeof AppAutopilotRoute
  '/board': typeof AppBoardRoute
  '/brief-history': typeof AppBriefHistoryRoute
  '/calendar': typeof AppCalendarRoute
  '/characters': typeof AppCharactersRoute
  '/content-score': typeof AppContentScoreRoute
  '/daily-brief': typeof AppDailyBriefRoute
  '/dm': typeof AppDmRoute
  '/hook-scoreboard': typeof AppHookScoreboardRoute
  '/ideator': typeof AppIdeatorRoute
  '/library': typeof AppLibraryRoute
  '/performance': typeof AppPerformanceRoute
  '/projects': typeof AppProjectsRoute
  '/resources': typeof AppResourcesRoute
  '/script': typeof AppScriptRoute
  '/series': typeof AppSeriesRoute
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/storyboard': typeof AppStoryboardRoute
  '/templates': typeof AppTemplatesRoute
  '/thumbnail-studio': typeof AppThumbnailStudioRoute
  '/video-analyzer': typeof AppVideoAnalyzerRoute
  '/video-prompt': typeof AppVideoPromptRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/apify-usage': typeof ApiApifyUsageRoute
  '/api/appearance': typeof ApiAppearanceRoute
  '/api/auto-queue': typeof ApiAutoQueueRoute
  '/api/board': typeof ApiBoardRoute
  '/api/board-attach': typeof ApiBoardAttachRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/dm': typeof ApiDmRoute
  '/api/frame-check': typeof ApiFrameCheckRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hook-script-writer': typeof ApiHookScriptWriterRoute
  '/api/hooks': typeof ApiHooksRoute
  '/api/ideator-generate': typeof ApiIdeatorGenerateRoute
  '/api/library-export': typeof ApiLibraryExportRoute
  '/api/library-import': typeof ApiLibraryImportRoute
  '/api/me': typeof ApiMeRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/pillars': typeof ApiPillarsRoute
  '/api/platform-variants': typeof ApiPlatformVariantsRoute
  '/api/post-performance': typeof ApiPostPerformanceRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/reader': typeof ApiReaderRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/run-pipeline': typeof ApiRunPipelineRoute
  '/api/score-content': typeof ApiScoreContentRoute
  '/api/scrape-competitor': typeof ApiScrapeCompetitorRoute
  '/api/scripts-list': typeof ApiScriptsListRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/settings-imagegen': typeof ApiSettingsImagegenRoute
  '/api/telegram-chat-id': typeof ApiTelegramChatIdRoute
  '/api/telegram-cron': typeof ApiTelegramCronRoute
  '/api/telegram-hook': typeof ApiTelegramHookRoute
  '/api/telegram-tasks': typeof ApiTelegramTasksRoute
  '/api/telegram-test': typeof ApiTelegramTestRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/thumbnail-prompt': typeof ApiThumbnailPromptRoute
  '/api/trend-spy': typeof ApiTrendSpyRoute
  '/api/trends': typeof ApiTrendsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/video-analyzer': typeof ApiVideoAnalyzerRoute
  '/api/video-gen-prompt': typeof ApiVideoGenPromptRoute
  '/api/visual-storyboard': typeof ApiVisualStoryboardRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/': typeof AppIndexRoute
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/resources/$id': typeof ApiResourcesIdRoute
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/autopilot': typeof AppAutopilotRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/brief-history': typeof AppBriefHistoryRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/characters': typeof AppCharactersRoute
  '/_app/content-score': typeof AppContentScoreRoute
  '/_app/daily-brief': typeof AppDailyBriefRoute
  '/_app/dm': typeof AppDmRoute
  '/_app/hook-scoreboard': typeof AppHookScoreboardRoute
  '/_app/ideator': typeof AppIdeatorRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/script': typeof AppScriptRoute
  '/_app/series': typeof AppSeriesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/storyboard': typeof AppStoryboardRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/thumbnail-studio': typeof AppThumbnailStudioRoute
  '/_app/video-analyzer': typeof AppVideoAnalyzerRoute
  '/_app/video-prompt': typeof AppVideoPromptRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/apify-usage': typeof ApiApifyUsageRoute
  '/api/appearance': typeof ApiAppearanceRoute
  '/api/auto-queue': typeof ApiAutoQueueRoute
  '/api/board': typeof ApiBoardRoute
  '/api/board-attach': typeof ApiBoardAttachRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/characters': typeof ApiCharactersRoute
  '/api/dm': typeof ApiDmRoute
  '/api/frame-check': typeof ApiFrameCheckRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/api/health': typeof ApiHealthRoute
  '/api/hook-script-writer': typeof ApiHookScriptWriterRoute
  '/api/hooks': typeof ApiHooksRoute
  '/api/ideator-generate': typeof ApiIdeatorGenerateRoute
  '/api/library-export': typeof ApiLibraryExportRoute
  '/api/library-import': typeof ApiLibraryImportRoute
  '/api/me': typeof ApiMeRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/pillars': typeof ApiPillarsRoute
  '/api/platform-variants': typeof ApiPlatformVariantsRoute
  '/api/post-performance': typeof ApiPostPerformanceRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/reader': typeof ApiReaderRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/run-pipeline': typeof ApiRunPipelineRoute
  '/api/score-content': typeof ApiScoreContentRoute
  '/api/scrape-competitor': typeof ApiScrapeCompetitorRoute
  '/api/scripts-list': typeof ApiScriptsListRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/settings-imagegen': typeof ApiSettingsImagegenRoute
  '/api/telegram-chat-id': typeof ApiTelegramChatIdRoute
  '/api/telegram-cron': typeof ApiTelegramCronRoute
  '/api/telegram-hook': typeof ApiTelegramHookRoute
  '/api/telegram-tasks': typeof ApiTelegramTasksRoute
  '/api/telegram-test': typeof ApiTelegramTestRoute
  '/api/telegram-webhook': typeof ApiTelegramWebhookRoute
  '/api/thumbnail-prompt': typeof ApiThumbnailPromptRoute
  '/api/trend-spy': typeof ApiTrendSpyRoute
  '/api/trends': typeof ApiTrendsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/video-analyzer': typeof ApiVideoAnalyzerRoute
  '/api/video-gen-prompt': typeof ApiVideoGenPromptRoute
  '/api/visual-storyboard': typeof ApiVisualStoryboardRoute
  '/api/workspace': typeof ApiWorkspaceRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/resources/$id': typeof ApiResourcesIdRoute
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autopilot'
    | '/board'
    | '/brief-history'
    | '/calendar'
    | '/characters'
    | '/content-score'
    | '/daily-brief'
    | '/dm'
    | '/hook-scoreboard'
    | '/ideator'
    | '/library'
    | '/performance'
    | '/projects'
    | '/resources'
    | '/script'
    | '/series'
    | '/settings'
    | '/sources'
    | '/storyboard'
    | '/templates'
    | '/thumbnail-studio'
    | '/video-analyzer'
    | '/video-prompt'
    | '/api/activity'
    | '/api/apify-usage'
    | '/api/appearance'
    | '/api/auto-queue'
    | '/api/board'
    | '/api/board-attach'
    | '/api/brief'
    | '/api/characters'
    | '/api/dm'
    | '/api/frame-check'
    | '/api/generate-image'
    | '/api/generate-plan'
    | '/api/health'
    | '/api/hook-script-writer'
    | '/api/hooks'
    | '/api/ideator-generate'
    | '/api/library-export'
    | '/api/library-import'
    | '/api/me'
    | '/api/notifications'
    | '/api/pillars'
    | '/api/platform-variants'
    | '/api/post-performance'
    | '/api/projects'
    | '/api/reader'
    | '/api/resources'
    | '/api/run-pipeline'
    | '/api/score-content'
    | '/api/scrape-competitor'
    | '/api/scripts-list'
    | '/api/search'
    | '/api/settings'
    | '/api/settings-imagegen'
    | '/api/telegram-chat-id'
    | '/api/telegram-cron'
    | '/api/telegram-hook'
    | '/api/telegram-tasks'
    | '/api/telegram-test'
    | '/api/telegram-webhook'
    | '/api/thumbnail-prompt'
    | '/api/trend-spy'
    | '/api/trends'
    | '/api/users'
    | '/api/video-analyzer'
    | '/api/video-gen-prompt'
    | '/api/visual-storyboard'
    | '/api/workspace'
    | '/api/library/$type'
    | '/api/resources/$id'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/autopilot'
    | '/board'
    | '/brief-history'
    | '/calendar'
    | '/characters'
    | '/content-score'
    | '/daily-brief'
    | '/dm'
    | '/hook-scoreboard'
    | '/ideator'
    | '/library'
    | '/performance'
    | '/projects'
    | '/resources'
    | '/script'
    | '/series'
    | '/settings'
    | '/sources'
    | '/storyboard'
    | '/templates'
    | '/thumbnail-studio'
    | '/video-analyzer'
    | '/video-prompt'
    | '/api/activity'
    | '/api/apify-usage'
    | '/api/appearance'
    | '/api/auto-queue'
    | '/api/board'
    | '/api/board-attach'
    | '/api/brief'
    | '/api/characters'
    | '/api/dm'
    | '/api/frame-check'
    | '/api/generate-image'
    | '/api/generate-plan'
    | '/api/health'
    | '/api/hook-script-writer'
    | '/api/hooks'
    | '/api/ideator-generate'
    | '/api/library-export'
    | '/api/library-import'
    | '/api/me'
    | '/api/notifications'
    | '/api/pillars'
    | '/api/platform-variants'
    | '/api/post-performance'
    | '/api/projects'
    | '/api/reader'
    | '/api/resources'
    | '/api/run-pipeline'
    | '/api/score-content'
    | '/api/scrape-competitor'
    | '/api/scripts-list'
    | '/api/search'
    | '/api/settings'
    | '/api/settings-imagegen'
    | '/api/telegram-chat-id'
    | '/api/telegram-cron'
    | '/api/telegram-hook'
    | '/api/telegram-tasks'
    | '/api/telegram-test'
    | '/api/telegram-webhook'
    | '/api/thumbnail-prompt'
    | '/api/trend-spy'
    | '/api/trends'
    | '/api/users'
    | '/api/video-analyzer'
    | '/api/video-gen-prompt'
    | '/api/visual-storyboard'
    | '/api/workspace'
    | '/'
    | '/api/library/$type'
    | '/api/resources/$id'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/autopilot'
    | '/_app/board'
    | '/_app/brief-history'
    | '/_app/calendar'
    | '/_app/characters'
    | '/_app/content-score'
    | '/_app/daily-brief'
    | '/_app/dm'
    | '/_app/hook-scoreboard'
    | '/_app/ideator'
    | '/_app/library'
    | '/_app/performance'
    | '/_app/projects'
    | '/_app/resources'
    | '/_app/script'
    | '/_app/series'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/storyboard'
    | '/_app/templates'
    | '/_app/thumbnail-studio'
    | '/_app/video-analyzer'
    | '/_app/video-prompt'
    | '/api/activity'
    | '/api/apify-usage'
    | '/api/appearance'
    | '/api/auto-queue'
    | '/api/board'
    | '/api/board-attach'
    | '/api/brief'
    | '/api/characters'
    | '/api/dm'
    | '/api/frame-check'
    | '/api/generate-image'
    | '/api/generate-plan'
    | '/api/health'
    | '/api/hook-script-writer'
    | '/api/hooks'
    | '/api/ideator-generate'
    | '/api/library-export'
    | '/api/library-import'
    | '/api/me'
    | '/api/notifications'
    | '/api/pillars'
    | '/api/platform-variants'
    | '/api/post-performance'
    | '/api/projects'
    | '/api/reader'
    | '/api/resources'
    | '/api/run-pipeline'
    | '/api/score-content'
    | '/api/scrape-competitor'
    | '/api/scripts-list'
    | '/api/search'
    | '/api/settings'
    | '/api/settings-imagegen'
    | '/api/telegram-chat-id'
    | '/api/telegram-cron'
    | '/api/telegram-hook'
    | '/api/telegram-tasks'
    | '/api/telegram-test'
    | '/api/telegram-webhook'
    | '/api/thumbnail-prompt'
    | '/api/trend-spy'
    | '/api/trends'
    | '/api/users'
    | '/api/video-analyzer'
    | '/api/video-gen-prompt'
    | '/api/visual-storyboard'
    | '/api/workspace'
    | '/_app/'
    | '/api/library/$type'
    | '/api/resources/$id'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiActivityRoute: typeof ApiActivityRoute
  ApiApifyUsageRoute: typeof ApiApifyUsageRoute
  ApiAppearanceRoute: typeof ApiAppearanceRoute
  ApiAutoQueueRoute: typeof ApiAutoQueueRoute
  ApiBoardRoute: typeof ApiBoardRoute
  ApiBoardAttachRoute: typeof ApiBoardAttachRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiCharactersRoute: typeof ApiCharactersRoute
  ApiDmRoute: typeof ApiDmRoute
  ApiFrameCheckRoute: typeof ApiFrameCheckRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGeneratePlanRoute: typeof ApiGeneratePlanRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHookScriptWriterRoute: typeof ApiHookScriptWriterRoute
  ApiHooksRoute: typeof ApiHooksRoute
  ApiIdeatorGenerateRoute: typeof ApiIdeatorGenerateRoute
  ApiLibraryExportRoute: typeof ApiLibraryExportRoute
  ApiLibraryImportRoute: typeof ApiLibraryImportRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiPillarsRoute: typeof ApiPillarsRoute
  ApiPlatformVariantsRoute: typeof ApiPlatformVariantsRoute
  ApiPostPerformanceRoute: typeof ApiPostPerformanceRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiReaderRoute: typeof ApiReaderRoute
  ApiResourcesRoute: typeof ApiResourcesRouteWithChildren
  ApiRunPipelineRoute: typeof ApiRunPipelineRoute
  ApiScoreContentRoute: typeof ApiScoreContentRoute
  ApiScrapeCompetitorRoute: typeof ApiScrapeCompetitorRoute
  ApiScriptsListRoute: typeof ApiScriptsListRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiSettingsImagegenRoute: typeof ApiSettingsImagegenRoute
  ApiTelegramChatIdRoute: typeof ApiTelegramChatIdRoute
  ApiTelegramCronRoute: typeof ApiTelegramCronRoute
  ApiTelegramHookRoute: typeof ApiTelegramHookRoute
  ApiTelegramTasksRoute: typeof ApiTelegramTasksRoute
  ApiTelegramTestRoute: typeof ApiTelegramTestRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiThumbnailPromptRoute: typeof ApiThumbnailPromptRoute
  ApiTrendSpyRoute: typeof ApiTrendSpyRoute
  ApiTrendsRoute: typeof ApiTrendsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiVideoAnalyzerRoute: typeof ApiVideoAnalyzerRoute
  ApiVideoGenPromptRoute: typeof ApiVideoGenPromptRoute
  ApiVisualStoryboardRoute: typeof ApiVisualStoryboardRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRouteWithChildren
  ApiLibraryTypeRoute: typeof ApiLibraryTypeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/autopilot': {
      id: '/_app/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AppAutopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brief-history': {
      id: '/_app/brief-history'
      path: '/brief-history'
      fullPath: '/brief-history'
      preLoaderRoute: typeof AppBriefHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/characters': {
      id: '/_app/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof AppCharactersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content-score': {
      id: '/_app/content-score'
      path: '/content-score'
      fullPath: '/content-score'
      preLoaderRoute: typeof AppContentScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-brief': {
      id: '/_app/daily-brief'
      path: '/daily-brief'
      fullPath: '/daily-brief'
      preLoaderRoute: typeof AppDailyBriefRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dm': {
      id: '/_app/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AppDmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hook-scoreboard': {
      id: '/_app/hook-scoreboard'
      path: '/hook-scoreboard'
      fullPath: '/hook-scoreboard'
      preLoaderRoute: typeof AppHookScoreboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideator': {
      id: '/_app/ideator'
      path: '/ideator'
      fullPath: '/ideator'
      preLoaderRoute: typeof AppIdeatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/script': {
      id: '/_app/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof AppScriptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series': {
      id: '/_app/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AppSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storyboard': {
      id: '/_app/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof AppStoryboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thumbnail-studio': {
      id: '/_app/thumbnail-studio'
      path: '/thumbnail-studio'
      fullPath: '/thumbnail-studio'
      preLoaderRoute: typeof AppThumbnailStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video-analyzer': {
      id: '/_app/video-analyzer'
      path: '/video-analyzer'
      fullPath: '/video-analyzer'
      preLoaderRoute: typeof AppVideoAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video-prompt': {
      id: '/_app/video-prompt'
      path: '/video-prompt'
      fullPath: '/video-prompt'
      preLoaderRoute: typeof AppVideoPromptRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apify-usage': {
      id: '/api/apify-usage'
      path: '/api/apify-usage'
      fullPath: '/api/apify-usage'
      preLoaderRoute: typeof ApiApifyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appearance': {
      id: '/api/appearance'
      path: '/api/appearance'
      fullPath: '/api/appearance'
      preLoaderRoute: typeof ApiAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-queue': {
      id: '/api/auto-queue'
      path: '/api/auto-queue'
      fullPath: '/api/auto-queue'
      preLoaderRoute: typeof ApiAutoQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board-attach': {
      id: '/api/board-attach'
      path: '/api/board-attach'
      fullPath: '/api/board-attach'
      preLoaderRoute: typeof ApiBoardAttachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters': {
      id: '/api/characters'
      path: '/api/characters'
      fullPath: '/api/characters'
      preLoaderRoute: typeof ApiCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dm': {
      id: '/api/dm'
      path: '/api/dm'
      fullPath: '/api/dm'
      preLoaderRoute: typeof ApiDmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frame-check': {
      id: '/api/frame-check'
      path: '/api/frame-check'
      fullPath: '/api/frame-check'
      preLoaderRoute: typeof ApiFrameCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-plan': {
      id: '/api/generate-plan'
      path: '/api/generate-plan'
      fullPath: '/api/generate-plan'
      preLoaderRoute: typeof ApiGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hook-script-writer': {
      id: '/api/hook-script-writer'
      path: '/api/hook-script-writer'
      fullPath: '/api/hook-script-writer'
      preLoaderRoute: typeof ApiHookScriptWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks': {
      id: '/api/hooks'
      path: '/api/hooks'
      fullPath: '/api/hooks'
      preLoaderRoute: typeof ApiHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ideator-generate': {
      id: '/api/ideator-generate'
      path: '/api/ideator-generate'
      fullPath: '/api/ideator-generate'
      preLoaderRoute: typeof ApiIdeatorGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library-export': {
      id: '/api/library-export'
      path: '/api/library-export'
      fullPath: '/api/library-export'
      preLoaderRoute: typeof ApiLibraryExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library-import': {
      id: '/api/library-import'
      path: '/api/library-import'
      fullPath: '/api/library-import'
      preLoaderRoute: typeof ApiLibraryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pillars': {
      id: '/api/pillars'
      path: '/api/pillars'
      fullPath: '/api/pillars'
      preLoaderRoute: typeof ApiPillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform-variants': {
      id: '/api/platform-variants'
      path: '/api/platform-variants'
      fullPath: '/api/platform-variants'
      preLoaderRoute: typeof ApiPlatformVariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-performance': {
      id: '/api/post-performance'
      path: '/api/post-performance'
      fullPath: '/api/post-performance'
      preLoaderRoute: typeof ApiPostPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reader': {
      id: '/api/reader'
      path: '/api/reader'
      fullPath: '/api/reader'
      preLoaderRoute: typeof ApiReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-pipeline': {
      id: '/api/run-pipeline'
      path: '/api/run-pipeline'
      fullPath: '/api/run-pipeline'
      preLoaderRoute: typeof ApiRunPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/score-content': {
      id: '/api/score-content'
      path: '/api/score-content'
      fullPath: '/api/score-content'
      preLoaderRoute: typeof ApiScoreContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-competitor': {
      id: '/api/scrape-competitor'
      path: '/api/scrape-competitor'
      fullPath: '/api/scrape-competitor'
      preLoaderRoute: typeof ApiScrapeCompetitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scripts-list': {
      id: '/api/scripts-list'
      path: '/api/scripts-list'
      fullPath: '/api/scripts-list'
      preLoaderRoute: typeof ApiScriptsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings-imagegen': {
      id: '/api/settings-imagegen'
      path: '/api/settings-imagegen'
      fullPath: '/api/settings-imagegen'
      preLoaderRoute: typeof ApiSettingsImagegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-chat-id': {
      id: '/api/telegram-chat-id'
      path: '/api/telegram-chat-id'
      fullPath: '/api/telegram-chat-id'
      preLoaderRoute: typeof ApiTelegramChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-cron': {
      id: '/api/telegram-cron'
      path: '/api/telegram-cron'
      fullPath: '/api/telegram-cron'
      preLoaderRoute: typeof ApiTelegramCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-hook': {
      id: '/api/telegram-hook'
      path: '/api/telegram-hook'
      fullPath: '/api/telegram-hook'
      preLoaderRoute: typeof ApiTelegramHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-tasks': {
      id: '/api/telegram-tasks'
      path: '/api/telegram-tasks'
      fullPath: '/api/telegram-tasks'
      preLoaderRoute: typeof ApiTelegramTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-test': {
      id: '/api/telegram-test'
      path: '/api/telegram-test'
      fullPath: '/api/telegram-test'
      preLoaderRoute: typeof ApiTelegramTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram-webhook': {
      id: '/api/telegram-webhook'
      path: '/api/telegram-webhook'
      fullPath: '/api/telegram-webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnail-prompt': {
      id: '/api/thumbnail-prompt'
      path: '/api/thumbnail-prompt'
      fullPath: '/api/thumbnail-prompt'
      preLoaderRoute: typeof ApiThumbnailPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trend-spy': {
      id: '/api/trend-spy'
      path: '/api/trend-spy'
      fullPath: '/api/trend-spy'
      preLoaderRoute: typeof ApiTrendSpyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trends': {
      id: '/api/trends'
      path: '/api/trends'
      fullPath: '/api/trends'
      preLoaderRoute: typeof ApiTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-analyzer': {
      id: '/api/video-analyzer'
      path: '/api/video-analyzer'
      fullPath: '/api/video-analyzer'
      preLoaderRoute: typeof ApiVideoAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-gen-prompt': {
      id: '/api/video-gen-prompt'
      path: '/api/video-gen-prompt'
      fullPath: '/api/video-gen-prompt'
      preLoaderRoute: typeof ApiVideoGenPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-storyboard': {
      id: '/api/visual-storyboard'
      path: '/api/visual-storyboard'
      fullPath: '/api/visual-storyboard'
      preLoaderRoute: typeof ApiVisualStoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/$type': {
      id: '/api/library/$type'
      path: '/api/library/$type'
      fullPath: '/api/library/$type'
      preLoaderRoute: typeof ApiLibraryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources/$id': {
      id: '/api/resources/$id'
      path: '/$id'
      fullPath: '/api/resources/$id'
      preLoaderRoute: typeof ApiResourcesIdRouteImport
      parentRoute: typeof ApiResourcesRoute
    }
    '/api/workspace/selected_idea': {
      id: '/api/workspace/selected_idea'
      path: '/selected_idea'
      fullPath: '/api/workspace/selected_idea'
      preLoaderRoute: typeof ApiWorkspaceSelected_ideaRouteImport
      parentRoute: typeof ApiWorkspaceRoute
    }
    '/api/library/$type/$id': {
      id: '/api/library/$type/$id'
      path: '/$id'
      fullPath: '/api/library/$type/$id'
      preLoaderRoute: typeof ApiLibraryTypeIdRouteImport
      parentRoute: typeof ApiLibraryTypeRoute
    }
  }
}

interface AppRouteChildren {
  AppAutopilotRoute: typeof AppAutopilotRoute
  AppBoardRoute: typeof AppBoardRoute
  AppBriefHistoryRoute: typeof AppBriefHistoryRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCharactersRoute: typeof AppCharactersRoute
  AppContentScoreRoute: typeof AppContentScoreRoute
  AppDailyBriefRoute: typeof AppDailyBriefRoute
  AppDmRoute: typeof AppDmRoute
  AppHookScoreboardRoute: typeof AppHookScoreboardRoute
  AppIdeatorRoute: typeof AppIdeatorRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppScriptRoute: typeof AppScriptRoute
  AppSeriesRoute: typeof AppSeriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppStoryboardRoute: typeof AppStoryboardRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppThumbnailStudioRoute: typeof AppThumbnailStudioRoute
  AppVideoAnalyzerRoute: typeof AppVideoAnalyzerRoute
  AppVideoPromptRoute: typeof AppVideoPromptRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutopilotRoute: AppAutopilotRoute,
  AppBoardRoute: AppBoardRoute,
  AppBriefHistoryRoute: AppBriefHistoryRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCharactersRoute: AppCharactersRoute,
  AppContentScoreRoute: AppContentScoreRoute,
  AppDailyBriefRoute: AppDailyBriefRoute,
  AppDmRoute: AppDmRoute,
  AppHookScoreboardRoute: AppHookScoreboardRoute,
  AppIdeatorRoute: AppIdeatorRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppScriptRoute: AppScriptRoute,
  AppSeriesRoute: AppSeriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppStoryboardRoute: AppStoryboardRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppThumbnailStudioRoute: AppThumbnailStudioRoute,
  AppVideoAnalyzerRoute: AppVideoAnalyzerRoute,
  AppVideoPromptRoute: AppVideoPromptRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiResourcesRouteChildren {
  ApiResourcesIdRoute: typeof ApiResourcesIdRoute
}

const ApiResourcesRouteChildren: ApiResourcesRouteChildren = {
  ApiResourcesIdRoute: ApiResourcesIdRoute,
}

const ApiResourcesRouteWithChildren = ApiResourcesRoute._addFileChildren(
  ApiResourcesRouteChildren,
)

interface ApiWorkspaceRouteChildren {
  ApiWorkspaceSelected_ideaRoute: typeof ApiWorkspaceSelected_ideaRoute
}

const ApiWorkspaceRouteChildren: ApiWorkspaceRouteChildren = {
  ApiWorkspaceSelected_ideaRoute: ApiWorkspaceSelected_ideaRoute,
}

const ApiWorkspaceRouteWithChildren = ApiWorkspaceRoute._addFileChildren(
  ApiWorkspaceRouteChildren,
)

interface ApiLibraryTypeRouteChildren {
  ApiLibraryTypeIdRoute: typeof ApiLibraryTypeIdRoute
}

const ApiLibraryTypeRouteChildren: ApiLibraryTypeRouteChildren = {
  ApiLibraryTypeIdRoute: ApiLibraryTypeIdRoute,
}

const ApiLibraryTypeRouteWithChildren = ApiLibraryTypeRoute._addFileChildren(
  ApiLibraryTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiActivityRoute: ApiActivityRoute,
  ApiApifyUsageRoute: ApiApifyUsageRoute,
  ApiAppearanceRoute: ApiAppearanceRoute,
  ApiAutoQueueRoute: ApiAutoQueueRoute,
  ApiBoardRoute: ApiBoardRoute,
  ApiBoardAttachRoute: ApiBoardAttachRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiCharactersRoute: ApiCharactersRoute,
  ApiDmRoute: ApiDmRoute,
  ApiFrameCheckRoute: ApiFrameCheckRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGeneratePlanRoute: ApiGeneratePlanRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHookScriptWriterRoute: ApiHookScriptWriterRoute,
  ApiHooksRoute: ApiHooksRoute,
  ApiIdeatorGenerateRoute: ApiIdeatorGenerateRoute,
  ApiLibraryExportRoute: ApiLibraryExportRoute,
  ApiLibraryImportRoute: ApiLibraryImportRoute,
  ApiMeRoute: ApiMeRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiPillarsRoute: ApiPillarsRoute,
  ApiPlatformVariantsRoute: ApiPlatformVariantsRoute,
  ApiPostPerformanceRoute: ApiPostPerformanceRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiReaderRoute: ApiReaderRoute,
  ApiResourcesRoute: ApiResourcesRouteWithChildren,
  ApiRunPipelineRoute: ApiRunPipelineRoute,
  ApiScoreContentRoute: ApiScoreContentRoute,
  ApiScrapeCompetitorRoute: ApiScrapeCompetitorRoute,
  ApiScriptsListRoute: ApiScriptsListRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiSettingsImagegenRoute: ApiSettingsImagegenRoute,
  ApiTelegramChatIdRoute: ApiTelegramChatIdRoute,
  ApiTelegramCronRoute: ApiTelegramCronRoute,
  ApiTelegramHookRoute: ApiTelegramHookRoute,
  ApiTelegramTasksRoute: ApiTelegramTasksRoute,
  ApiTelegramTestRoute: ApiTelegramTestRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiThumbnailPromptRoute: ApiThumbnailPromptRoute,
  ApiTrendSpyRoute: ApiTrendSpyRoute,
  ApiTrendsRoute: ApiTrendsRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiVideoAnalyzerRoute: ApiVideoAnalyzerRoute,
  ApiVideoGenPromptRoute: ApiVideoGenPromptRoute,
  ApiVisualStoryboardRoute: ApiVisualStoryboardRoute,
  ApiWorkspaceRoute: ApiWorkspaceRouteWithChildren,
  ApiLibraryTypeRoute: ApiLibraryTypeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
