/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ApiWorkspaceSelected_ideaRouteImport } from './routes/api/workspace.selected_idea'
import { Route as ApiLibraryTypeRouteImport } from './routes/api/library.$type'
import { Route as ApiLibraryTypeIdRouteImport } from './routes/api/library.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceSelected_ideaRoute =
  ApiWorkspaceSelected_ideaRouteImport.update({
    id: '/api/workspace/selected_idea',
    path: '/api/workspace/selected_idea',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLibraryTypeRoute = ApiLibraryTypeRouteImport.update({
  id: '/api/library/$type',
  path: '/api/library/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryTypeIdRoute = ApiLibraryTypeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiLibraryTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/library/$type': typeof ApiLibraryTypeRouteWithChildren
  '/api/workspace/selected_idea': typeof ApiWorkspaceSelected_ideaRoute
  '/api/library/$type/$id': typeof ApiLibraryTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/activity'
    | '/api/projects'
    | '/api/search'
    | '/api/library/$type'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/activity'
    | '/api/projects'
    | '/api/search'
    | '/api/library/$type'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/api/activity'
    | '/api/projects'
    | '/api/search'
    | '/api/library/$type'
    | '/api/workspace/selected_idea'
    | '/api/library/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiActivityRoute: typeof ApiActivityRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiLibraryTypeRoute: typeof ApiLibraryTypeRouteWithChildren
  ApiWorkspaceSelected_ideaRoute: typeof ApiWorkspaceSelected_ideaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/selected_idea': {
      id: '/api/workspace/selected_idea'
      path: '/api/workspace/selected_idea'
      fullPath: '/api/workspace/selected_idea'
      preLoaderRoute: typeof ApiWorkspaceSelected_ideaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/$type': {
      id: '/api/library/$type'
      path: '/api/library/$type'
      fullPath: '/api/library/$type'
      preLoaderRoute: typeof ApiLibraryTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/$type/$id': {
      id: '/api/library/$type/$id'
      path: '/$id'
      fullPath: '/api/library/$type/$id'
      preLoaderRoute: typeof ApiLibraryTypeIdRouteImport
      parentRoute: typeof ApiLibraryTypeRoute
    }
  }
}

interface ApiLibraryTypeRouteChildren {
  ApiLibraryTypeIdRoute: typeof ApiLibraryTypeIdRoute
}

const ApiLibraryTypeRouteChildren: ApiLibraryTypeRouteChildren = {
  ApiLibraryTypeIdRoute: ApiLibraryTypeIdRoute,
}

const ApiLibraryTypeRouteWithChildren = ApiLibraryTypeRoute._addFileChildren(
  ApiLibraryTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiActivityRoute: ApiActivityRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiLibraryTypeRoute: ApiLibraryTypeRouteWithChildren,
  ApiWorkspaceSelected_ideaRoute: ApiWorkspaceSelected_ideaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
